# Generated by Django 4.2.25 on 2025-11-10 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0002_series_author_seriesview_seriesrating_chapterview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('novel_url', models.URLField(help_text='URL of the novel page to scrape', max_length=2048)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scraping', 'Scraping Novel Info'), ('translating', 'Translating Chapters'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('korean_title', models.CharField(blank=True, max_length=255, null=True)),
                ('korean_author', models.CharField(blank=True, max_length=255, null=True)),
                ('korean_genre', models.CharField(blank=True, max_length=100, null=True)),
                ('korean_description', models.TextField(blank=True, null=True)),
                ('english_title', models.CharField(blank=True, max_length=255, null=True)),
                ('english_author', models.CharField(blank=True, max_length=255, null=True)),
                ('english_genre', models.CharField(blank=True, max_length=100, null=True)),
                ('english_description', models.TextField(blank=True, null=True)),
                ('chapters_requested', models.IntegerField(help_text='Number of chapters to translate', validators=[django.core.validators.MinValueValidator(1)])),
                ('chapters_completed', models.IntegerField(default=0, help_text='Number of chapters successfully translated')),
                ('chapters_failed', models.IntegerField(default=0, help_text='Number of chapters that failed')),
                ('current_operation', models.CharField(blank=True, help_text='Current operation being performed', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job completed or failed', null=True)),
                ('imported_series', models.ForeignKey(blank=True, help_text='Series created from this translation job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_jobs', to='library.series')),
            ],
            options={
                'db_table': 'translationjob',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslatedChapterCache',
            fields=[
                ('cache_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('chapter_url', models.URLField(help_text='Original chapter URL', max_length=2048)),
                ('korean_title', models.CharField(max_length=255)),
                ('korean_content', models.TextField()),
                ('english_title', models.CharField(blank=True, max_length=255, null=True)),
                ('english_content_raw', models.TextField(blank=True, help_text='Raw translation before polishing', null=True)),
                ('english_content_final', models.TextField(blank=True, help_text='Final polished translation', null=True)),
                ('word_count', models.IntegerField(blank=True, help_text='Word count of final English content', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scraped', 'Scraped'), ('translated', 'Translated'), ('polished', 'Polished'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_chapter', models.ForeignKey(blank=True, help_text='Chapter created from this cache', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_cache', to='library.chapter')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_chapters', to='translator.translationjob')),
            ],
            options={
                'db_table': 'translatedchaptercache',
                'ordering': ['job', 'chapter_number'],
                'unique_together': {('job', 'chapter_number')},
            },
        ),
    ]
