# Generated by Django 4.2.25 on 2025-11-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationjob',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Cover image URL from source', max_length=2048, null=True),
        ),
    ]
