# Generated by Django 4.2.25 on 2025-11-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_translationjob_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationjob',
            name='prompt_dictionary',
            field=models.JSONField(blank=True, help_text='Dictionary of terms for consistent translation (e.g., character names, organizations, special terms)', null=True),
        ),
    ]
