# Generated by Django 4.2.25 on 2025-11-11 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_series_author_seriesview_seriesrating_chapterview'),
        ('users', '0003_alter_role_options_alter_role_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_records', to='library.chapter')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='library.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'readinghistory',
                'ordering': ['-last_read_at'],
                'indexes': [models.Index(fields=['user', 'series'], name='readinghist_user_id_fb7d7f_idx'), models.Index(fields=['user', '-last_read_at'], name='readinghist_user_id_0c3610_idx')],
                'unique_together': {('user', 'series')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='library.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmark',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'series'], name='bookmark_user_id_e01407_idx')],
                'unique_together': {('user', 'series')},
            },
        ),
    ]
